name: CI - Build & Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: MyDevSecOpsPipeline   # 🔥 IMPORTANT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug project structure
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t mydevsecops:${{ github.sha }} .

      # 🔐 Optional: Trivy scan (recommended for DevSecOps)
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: mydevsecops:${{ github.sha }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH